- name: variables
  hosts: localhost
  vars:
    course: "Ansible"
    Trainer: "abc"
    Duration: "120hrs"
  tasks: 
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning{{course}} from {{trainer}}, Duration is {{Duration}}"
      
